export const EMPLOYEES = [
  "Lucas DOSSO",
  "Salvatore MACRI",
  "Oleksandr FESENKO",
  "Maxime CAHIER",
  "Tiberius SCLIPCEA",
  "Oussama RABOUN",
  "Manel REBHI",
  "Ammar AHMED",
  "Fernando DE LA GUARDIA",
  "Elise VERSINI",
  "Rebecca FAHED",
  "Hajar FIOUZ",
  "Laura ZITH",
  "Giada SCAROLA",
  "Adrien CHABANEL",
  "Benjamin AZOR",
  "Amir Mohammad FOROOZAN",
  "Yoana GUEGUEN",
  "Marengo Digital",
  "Clementine PITHON",
  "LYPIRIDOU SOFIA",
  "DOS REIS PEREIRA AMANDA",
]

export const ADMIN_NAME = "Laure COHEN"
